
# time out command
command_timeout = 1000

# Inserts a blank line between shell prompts
add_newline = true

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[â‰»âŠ²â‹—](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# error_symbol = "[âœ—](bold red) "
error_symbol = "[-_-](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

#[custom.docker]
#files = ["docker-compose.yml"]
#format = "via [ğŸ‹ $context](blue bold)"

